name: Spark ETL Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install PySpark
        run: pip install pyspark
      - name: Run Spark Pipeline
        run: python spark_pipeline.py
